### PR TITLE
fix: correctly display total order amount

### LINKED ISSUE #201: Orders table total only reflect first payment
## Issue Description
If an order is split into more than one type of payment the order total displayed on the orders table will only reflect the amount for the first payment made rather than the entire order.

## Steps to Reproduce
1. Add a product to cart
2. Go to checkout
3. Make a partial payment
4. Complete payment with another form of payment (or same one, key is to split payment into more than one installment)
 5. Check order on orders table from the admin

## Actual results
total displayed corresponds to the amount on the first payment, rather than the order as a total

### PR DESCRIPTION
**Pull request by willopez**
Resolves #201 
Impact: **minor**
Type: **bugfix**

## Issue
In the orders table, the order total only took into account the amount of the first payment.

## Solution
Calculate an order's total by summing all payments

## Testing
1. Place an order and split the payment into multiple payments
2. Verify to order total is correctly rendered in the orders table.

### CODE REVIEW

**Review by manueldelreal — APPROVED** [review]
Total is now reflected on table rather than just the first payment.

File: imports/plugins/core/orders/client/components/DataTable/OrderTotalCell.js [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+ * @name OrderTotalCell
+ * @param {Object} row A react-table row object
+ * @return {React.Component} A React component to render an order's total
+ */
+function OrderTotalCell({ row }) {
+  // Sum up all the payments on an orders. Since the API returns
+  // the payments already formatted, just use the currency symbol provided.
+  const currencySymbol = row.original.payments[0].amount.displayAmount.charAt(0);
+  const reducer = (accumulator, value) => accumulator + Number.parseFloat(value.amount.displayAmount.slice(1));
+  const total = row.original.payments.reduce(reducer, 0);
```
Comment (mikemurray) [inline imports/plugins/core/orders/client/components/DataTable/OrderTotalCell.js]: @willopez are you trying to show the order total or the total amount paid for the order. If it's the order total then you can get that from the `summary` object on the order.

Either way, the total should come from the API, rather than being calculated on the fly there.

**Review by mikemurray — DISMISSED** [review]

File: imports/plugins/core/orders/client/components/DataTable/OrderTotalCell.js (hunk 1 above)
Comment (willopez) [reply imports/plugins/core/orders/client/components/DataTable/OrderTotalCell.js]: Tru story, now using order total provided by API

**Review by mikemurray — APPROVED** [review]
👍
