### PR TITLE
Product media fixes

### LINKED ISSUE #236: Revisit product media gallery editor
## Issues

Issues that arise from the new product editor from this PR: https://github.com/reactioncommerce/reaction-admin/pull/188

- [x] Reloading data after uploading an image doesn't work due to the delay from upload to converting and saving with sharp. https://github.com/reactioncommerce/reaction-admin/pull/188#issuecomment-594101238
- [x] The display of the media might be inaccurate. The product may be showing images from the variants as well.

- [x] Priority field doesn't work

### PR DESCRIPTION
**Pull request by willopez**
Resolves #236
Impact: **minor**
Type: **bugfix**

## Issue
There are several issues with the product medial gallery, more details provided in #236 

## Solution
Part of the solution is to refetch product data after images are added to a product. 

## Breaking changes
None

## Testing
1. Upload multiple media items for a product
2. Verify all media is uploaded and displayed correctly
3. Remove media items from a product
4. Verify media items are correctly removed and UI updates correctly
5. Set new priorities on various media items
6. Verify new media item priorities are set correctly

### CODE REVIEW

File: imports/plugins/core/ui/client/components/media/mediaUploader.js [hunk 1]
```diff
@@ -59,9 +59,43 @@ function MediaUploader(props) {
...
+            clearTimeout(timerId);
+          }
+        }, 500);
+
+        // Stop polling after 20 seconds
+        setTimeout(() => {
+          clearTimeout(timerId);
+          setIsUploading(false);
+        }, 20000);
+
```
Comment (mikemurray) [inline imports/plugins/core/ui/client/components/media/mediaUploader.js:120]: I'm seeing the progress bar sick around for the full 20 seconds on variants/options, even if the media shows up before then. Maybe something is off with the `isAllMediaProcessed` check above.

File: imports/plugins/core/ui/client/components/media/mediaUploader.js [hunk 2]
```diff
@@ -59,9 +59,43 @@ function MediaUploader(props) {
...
+            // If a url has been generated, then these media items has been processed successfully.
+            return mediaItem && mediaItem.thumbnailUrl !== String(null);
+          });
+
+          if (isAllMediaProcessed) {
+            setIsUploading(false);
+            clearTimeout(timerId);
+          }
+        }, 500);
```
Comment (mikemurray) [inline imports/plugins/core/ui/client/components/media/mediaUploader.js]: I think 500ms is too fast to hit the API. Since this is a hack I'd say 2s would be fine since it seems to take a few seconds per upload for me before I get results.

**Review by mikemurray — CHANGES_REQUESTED** [review]

File: imports/plugins/core/ui/client/components/media/mediaUploader.js (hunk 2 above)
Comment (janus-reith) [reply imports/plugins/core/ui/client/components/media/mediaUploader.js]: I'd make it 3-5 s :D
For larger images, even 2s could be too short.

File: imports/plugins/core/ui/client/components/media/mediaUploader.js (hunk 1 above)
Comment (willopez) [reply imports/plugins/core/ui/client/components/media/mediaUploader.js:120]: fixed

File: imports/plugins/core/ui/client/components/media/mediaUploader.js (hunk 2 above)
Comment (willopez) [reply imports/plugins/core/ui/client/components/media/mediaUploader.js]: Changed it to 2 seconds, we'll see if this is sufficient for most cases. If not, then we can increase it.

**Review by mikemurray — APPROVED** [review]
👍
