### PR TITLE
Fix setting views various issues reported in #238

### LINKED ISSUE #238: Issues found with new settings pages
- [x] Couldn't save the main shop settings form without adding a shop email. Initially, it didn't seem to give me an error. After entering the email, the forms save consistently. Even if I remove the shop email.

- [ ]  Can scroll the layout container. This is hard reproduce, and may just be a general layout issue. Double-check that no other settings subpage or template does overflow scroll other than the `ContentViewPrimaryDetailLayout` component.
image

- [x] Some pages need bottom padding
image

- Payment (maybe but it too short to matter)
- Taxes
- Shipping
- System information
- Address validation

Each card either needs margin-bottom, or you can do this to make it automatic
```
                <Blocks region="RegionName">
                  {(blocks) =>
                    blocks.map((block, index) => (
                      <Box paddingBottom={2} key={index}>
                        {block}
                      </Box>
                    ))
                  }
                </Blocks>
```

- [x] All "save" button should say "save changes" i18nkey "app.saveChanges". Some do, but others don't

- [x] Consider disabling save buttons if the form isn't dirty. `isDirty` is available from the `useReactoForm` hook. `disabled={!isDirty || isSubmitting}`

- [x] Cancel button in address dialog should be primary. The secondary blue pops

- [x] The loading spinners need some height.

- [x] Sidebar list should highlight the active item

### PR DESCRIPTION
**Pull request by willopez**
Resolves #238 
Impact: **minor**
Type: **bugfix|refactor**

## Issue
There are various issues with the new settings views, this PR seeks to fix all those and add some necessary CSS styles polish.

## Testing
1. Clicking on a setting link should add a selected style to the link
2. Verify all other styling issues reported on #238 are resolved.

### CODE REVIEW

File: imports/plugins/core/dashboard/client/components/SettingsList.js [hunk 1]
```diff
@@ -27,34 +47,37 @@ const useStyles = makeStyles((theme) => ({
...
-        <ListItemText
-          primary={i18next.t(setting.sidebarI18nLabel)}
-        />
-      </ListItem>
+        <ListItem
+          component="nav"
+          ContainerProps={{
+            className: classes.listItemContainer
+          }}
+          button={false}
```
Comment (mikemurray) [inline imports/plugins/core/dashboard/client/components/SettingsList.js:66]: The `button` prop should be true here. We should not be doing custom CSS for these list items and follow the internal design/theme for the `ListItem` component. The alternative needs to be that we don't use NavLink and manually do the `history.push` and the active class.

**Review by mikemurray — CHANGES_REQUESTED** [review]

File: imports/plugins/core/dashboard/client/components/SettingsList.js (hunk 1 above)
Comment (mikemurray) [reply imports/plugins/core/dashboard/client/components/SettingsList.js:66]: I added a ticket in catalyst to revisit the list styles as well because every instance we have of them (main nav, products editor, settings) are all custom jobs, but they should be more reusable.

https://github.com/reactioncommerce/catalyst/issues/155

**Review by mikemurray — APPROVED** [review]
👍 We can revisit the nav issues in Catalyst with a reusable component
